version: '3'
services:
  #Administration Api
  promocode-factory-administration-api:
    build: src/Otus.Teaching.Pcf.Administration/
    container_name: 'promocode-factory-administration-api'
    restart: always
    ports:
      - "8091:80"
    environment:
      - "AdministrationMongoDatabaseSettings:ConnectionString=mongodb://localhost:27017"
      - "AdministrationMongoDatabaseSettings:DatabaseName=AdministrationDb"           
    depends_on: 
      - promocode-factory-administration-mongo
  #Administration Db
  promocode-factory-administration-db:
    image: "postgres:9.6.17"
    container_name: 'promocode-factory-administration-db'
    restart: always 
    ports:
      - 5433:5432
    environment: 
      - POSTGRES_PASSWORD=docker
  #Administration mongo:
  promocode-factory-administration-mongo:
    image: mongo:4.2.3
    container_name: 'promocode-factory-administration-mongo'
    restart: always 
    ports:
      - 27017:27017

  #ReceivingFromPartner Api
  promocode-factory-receiving-from-partner-api:
    build: src/Otus.Teaching.Pcf.ReceivingFromPartner/
    container_name: 'promocode-factory-receiving-from-partner-api'
    restart: always
    ports:
      - "8092:80"
    environment:
      - "ConnectionStrings:PromocodeFactoryReceivingFromPartnerDb=Host=promocode-factory-receiving-from-partner-db;Database=promocode_factory_receiving_from_partner_db;Username=postgres;Password=docker"
      - "IntegrationSettings:GivingToCustomerApiUrl=http://promocode-factory-giving-to-customer-api"    
      - "IntegrationSettings:AdministrationApiUrl=http://promocode-factory-administration-api"       
    depends_on: 
      - promocode-factory-receiving-from-partner-db
  #ReceivingFromPartner Db
  promocode-factory-receiving-from-partner-db:
    image: "postgres:9.6.17"
    container_name: 'promocode-factory-receiving-from-partner-db'
    restart: always 
    ports:
      - 5434:5432
    environment: 
      - POSTGRES_PASSWORD=docker
  
  #GivingToCustomer Api
  promocode-factory-giving-to-customer-api:
    build: src/Otus.Teaching.Pcf.GivingToCustomer/
    container_name: 'promocode-factory-giving-to-customer-api'
    restart: always
    ports:
      - "8093:80"
    environment:
      - "GivingToCustomerMongoDatabaseSettings:ConnectionString=mongodb://localhost:27018"        
      - "GivingToCustomerMongoDatabaseSettings:DatabaseName=GivingToCustomerDb"        
    depends_on: 
      - promocode-factory-giving-to-customer-mongo
  #GivingToCustomer Db
  promocode-factory-giving-to-customer-db:
    image: "postgres:9.6.17"
    container_name: 'promocode-factory-giving-to-customer-db'
    restart: always 
    ports:
      - 5435:5432
    environment: 
      - POSTGRES_PASSWORD=docker
  #GivingToCustomer mongo:
  promocode-factory-giving-to-customer-mongo:
    image: mongo:4.2.3
    container_name: 'promocode-factory-giving-to-customer-mongo'
    restart: always 
    ports:
      - 27018:27017